import XCTest
import ProbablySudokuEngine
@testable import ProbablySudoku

@MainActor
final class HandArrangementTests: XCTestCase {
    func testAllArrangementsLeaveCanonicalHandGameAndEveryRandomStreamUntouched() throws {
        let model = try makeModel()
        let game = model.game
        let canonical = model.handCards
        let streams = streamStates(game)
        for arrangement in [GameModel.HandArrangement.ascending, .descending, .random, .random] {
            model.arrangeHand(arrangement)
            XCTAssertEqual(model.handCards, canonical)
            XCTAssertEqual(model.hand, canonical.map(\.digit))
            XCTAssertEqual(streamStates(model.game), streams)
            XCTAssertNil(RunStore.conflict(local: game, remote: model.game))
            assertCompletePermutation(model)
        }
    }

    func testAscendingAndDescendingPreserveDuplicateSelectionAndArrivalIdentities() throws {
        let model = try makeModel()
        let selected = model.handCards[2]
        model.tapHandCard(selected.id)
        let canonical = model.handCards
        for arrangement in [GameModel.HandArrangement.ascending, .descending, .random] {
            model.arrangeHand(arrangement)
            XCTAssertEqual(model.selectedHandIndex, 2)
            XCTAssertEqual(model.handCards[2].id, selected.id)
            XCTAssertEqual(model.handCards, canonical, "Arrivals and IDs cannot be regenerated by sorting")
            if arrangement == .ascending {
                XCTAssertEqual(model.displayedHandCards.map(\.digit), model.hand.sorted())
            } else if arrangement == .descending {
                XCTAssertEqual(model.displayedHandCards.map(\.digit), model.hand.sorted(by: >))
            }
        }
    }

    func testSortedPlaceConsumesTheSelectedCopyAtItsCanonicalIndex() throws {
        let model = try makeModel()
        model.arrangeHand(.ascending)
        let selected = model.handCards[2]
        let otherDuplicate = model.handCards[0].id
        let square = try blank(in: model, matching: selected.digit)
        model.tapHandCard(selected.id)
        XCTAssertEqual(model.selectedHandIndex, 2)
        model.tapSquare(square)
        XCTAssertEqual(model.puzzle?.board[square], selected.digit)
        XCTAssertFalse(model.handCards.contains { $0.id == selected.id })
        XCTAssertTrue(model.handCards.contains { $0.id == otherDuplicate })
        XCTAssertEqual(model.displayedHandCards.map(\.digit), model.hand.sorted())
        assertCompletePermutation(model)
    }

    func testSortedTossConsumesTheSelectedCopyAndPublishesItsMotionIdentity() throws {
        let model = try makeModel()
        model.arrangeHand(.descending)
        let selected = model.handCards[2]
        let survivors = model.handCards.filter { $0.id != selected.id }
        model.tapHandCard(selected.id)
        model.tossSelected()
        XCTAssertEqual(model.handCards, survivors)
        XCTAssertEqual(model.numberReturns.last?.handCardIDs, [selected.id])
        XCTAssertEqual(model.numberReturns.last?.digits, [selected.digit])
        assertCompletePermutation(model)
    }

    func testSortedClueTargetsTheSelectedCardWithoutConsumingEitherDuplicate() throws {
        let model = try makeModel()
        model.arrangeHand(.ascending)
        let selected = model.handCards[2]
        let before = model.handCards
        model.chooseClue()
        model.tapHandCard(selected.id)
        XCTAssertEqual(model.selectedHandIndex, 2)
        XCTAssertEqual(model.handCards, before)
        let square = try XCTUnwrap(model.puzzle?.clueReveals.first)
        XCTAssertEqual(model.puzzle?.board.correctDigit(at: square), selected.digit)
        XCTAssertNil(model.puzzle?.board[square])
        XCTAssertTrue(model.isClueDestination(square))
        model.tapSquare(square)
        XCTAssertFalse(model.handCards.contains { $0.id == selected.id })
        XCTAssertTrue(model.handCards.contains { $0.id == before[0].id })
    }

    func testAnchoredMenuPreservesArmedPeekAndThenItsSelectedDuplicateHint() throws {
        let model = try makeModel()
        model.qaSetBuff(Buffs.peek)
        let peekID = try XCTUnwrap(model.run.buffs.first?.id)
        let presenter = HandArrangementPresenter()
        let owner = UUID()
        let anchor = CGRect(x: 340, y: 560, width: 44, height: 44)
        XCTAssertTrue(model.useBuff(at: 0))
        let beforeReveal = try model.game.encoded()
        let canonical = model.handCards
        let selected = canonical[2]
        for arrangement in [GameModel.HandArrangement.ascending, .descending, .random] {
            presenter.toggle(owner: owner, anchor: anchor, model: model)
            XCTAssertNotNil(presenter.session)
            XCTAssertTrue(model.isChoosingClue, "Opening the menu must preserve an armed Peek")
            presenter.choose(arrangement, owner: owner)
            XCTAssertNil(presenter.session)
            XCTAssertTrue(model.isChoosingClue, "Choosing an arrangement must preserve Clue targeting")
            XCTAssertEqual(model.pendingPeekID, peekID)
            XCTAssertEqual(model.handCards, canonical)
            XCTAssertNil(model.selectedHandIndex)
            XCTAssertEqual(try model.game.encoded(), beforeReveal)
        }
        model.tapHandCard(selected.id)
        XCTAssertNil(model.pendingPeekID)
        XCTAssertTrue(model.run.buffs.isEmpty)
        let destination = try XCTUnwrap(model.puzzle?.clueReveals.first)
        let revealed = try model.game.encoded()
        for arrangement in [GameModel.HandArrangement.descending, .ascending, .random] {
            presenter.toggle(owner: owner, anchor: anchor, model: model)
            XCTAssertNotNil(presenter.session)
            presenter.choose(arrangement, owner: owner)
            XCTAssertNil(presenter.session)
            XCTAssertEqual(model.handArrangement, arrangement)
            XCTAssertEqual(model.selectedHandIndex, 2)
            XCTAssertEqual(model.handCards[2].id, selected.id)
            XCTAssertTrue(model.isClueDestination(destination))
            XCTAssertEqual(try model.game.encoded(), revealed)
        }
    }

    func testMenuDismissalAndSameButtonToggleLeaveSelectedDuplicateAndRunUntouched() throws {
        let model = try makeModel()
        let presenter = HandArrangementPresenter()
        let owner = UUID()
        let anchor = CGRect(x: 340, y: 560, width: 44, height: 44)
        let selected = model.handCards[2]
        model.tapHandCard(selected.id)
        let before = try model.game.encoded()
        let canonical = model.handCards
        let order = model.handPresentationOrder
        presenter.toggle(owner: owner, anchor: anchor, model: model)
        XCTAssertNotNil(presenter.session)
        presenter.dismiss(owner: UUID())
        XCTAssertNotNil(presenter.session, "Another disappearing Hand cannot dismiss this menu")
        presenter.toggle(owner: owner, anchor: anchor, model: model)
        XCTAssertNil(presenter.session, "The same button closes its menu")
        presenter.toggle(owner: owner, anchor: anchor, model: model)
        presenter.dismiss() // Outside-tap, Escape, cover, and scene dismissal share this path.
        XCTAssertNil(presenter.session)
        presenter.choose(.ascending, owner: owner) // An already dismissed choice is inert.
        XCTAssertEqual(model.handArrangement, .dealt)
        XCTAssertEqual(model.handCards, canonical)
        XCTAssertEqual(model.handPresentationOrder, order)
        XCTAssertEqual(model.selectedHandIndex, 2)
        XCTAssertEqual(model.handCards[2].id, selected.id)
        XCTAssertEqual(try model.game.encoded(), before)
    }

    func testMenuRejectsUnlaidOutAnchorsAndAChoiceFromThePreviousTurn() throws {
        let model = try makeModel()
        let presenter = HandArrangementPresenter()
        let owner = UUID()
        presenter.toggle(owner: owner, anchor: .zero, model: model)
        XCTAssertNil(presenter.session)
        presenter.toggle(owner: owner, anchor: CGRect(x: 340, y: 560, width: 44, height: 44), model: model)
        XCTAssertNotNil(presenter.session)
        let turn = model.puzzle?.turnNumber
        model.endTurn()
        XCTAssertNotEqual(model.puzzle?.turnNumber, turn)
        let before = try model.game.encoded()
        let order = model.handPresentationOrder
        presenter.choose(.descending, owner: owner)
        XCTAssertNil(presenter.session)
        XCTAssertEqual(model.handArrangement, .dealt)
        XCTAssertEqual(model.handPresentationOrder, order)
        XCTAssertEqual(try model.game.encoded(), before)
    }

    func testHandyDandyBlocksOneDuplicateThroughSortingAndSurvivorIndexChanges() throws {
        var run = try fixture().run
        var restriction = BossTurnState()
        restriction.blockedHandIndices = [2]
        run.puzzle?.boss = .handyDandy
        run.puzzle?.bossTurn = restriction
        let model = GameModel(resuming: Game(run: run), savesProgress: false)
        let blocked = model.handCards[2].id
        let free = model.handCards[0].id
        model.arrangeHand(.ascending)
        XCTAssertTrue(model.isBlocked(handIndex: try XCTUnwrap(model.canonicalHandIndex(for: blocked))))
        XCTAssertFalse(model.isBlocked(handIndex: try XCTUnwrap(model.canonicalHandIndex(for: free))))
        model.tapHandCard(blocked)
        XCTAssertTrue(model.message?.localizedCaseInsensitiveContains("cannot be played or Tossed") == true)
        XCTAssertFalse(model.canToss)
        let before = model.game
        model.tossSelected()
        XCTAssertNil(RunStore.conflict(local: before, remote: model.game))
        model.tapHandCard(free)
        XCTAssertTrue(model.canToss)
        model.tossSelected()
        let shifted = try XCTUnwrap(model.canonicalHandIndex(for: blocked))
        XCTAssertEqual(shifted, 1)
        XCTAssertTrue(model.isBlocked(handIndex: shifted))
        XCTAssertTrue(model.puzzle?.isTossBlocked(handIndex: shifted) == true)
        assertCompletePermutation(model)
    }

    func testObstacleBlocksBothDuplicateDigitsButStillAllowsTheSelectedCopyToBeTossed() throws {
        var run = try fixture().run
        let digit = try XCTUnwrap(run.puzzle?.hand.first)
        run.puzzle?.obstacleBlockedDigits = [digit]
        let model = GameModel(resuming: Game(run: run), savesProgress: false)
        let selected = model.handCards[2].id
        model.arrangeHand(.descending)
        XCTAssertTrue(model.isBlocked(handIndex: 0))
        XCTAssertTrue(model.isBlocked(handIndex: 2))
        XCTAssertFalse(model.puzzle?.isTossBlocked(handIndex: 2) == true)
        model.tapHandCard(selected)
        XCTAssertTrue(model.canToss)
        model.tossSelected()
        XCTAssertFalse(model.handCards.contains { $0.id == selected })
        XCTAssertEqual(model.hand.filter { $0 == digit }.count, 1)
    }

    func testRandomOrderIsStableAcrossRefreshAndAppendsBonusDrawsWithoutReshuffling() throws {
        let model = try makeModel()
        model.arrangeHand(.random)
        let order = model.handPresentationOrder
        for _ in 0..<5 {
            XCTAssertEqual(model.displayedHandCards.map(\.id), order)
        }
        model.endTurn()
        XCTAssertEqual(Array(model.handPresentationOrder.prefix(order.count)), order)
        model.qaSetBuff("bf_lucky_dip")
        let beforeDraw = model.handPresentationOrder
        XCTAssertTrue(model.useBuff(at: 0))
        XCTAssertEqual(Array(model.handPresentationOrder.prefix(beforeDraw.count)), beforeDraw)
        XCTAssertGreaterThan(model.handCards.count, try XCTUnwrap(model.puzzle?.handSize))
        assertCompletePermutation(model)
    }

    func testSortedJadeReturnKeepsTheExactCardAndItsMotionTarget() throws {
        var game = try fixture()
        let digit = try XCTUnwrap(game.puzzle?.hand[2])
        let square = try XCTUnwrap(game.puzzle?.board.blanks.first {
            game.puzzle?.board.correctDigit(at: $0) != digit
        })
        game.qaSetMarker(Markers.jade, at: square)
        let model = GameModel(resuming: game, savesProgress: false)
        let canonical = model.handCards
        let returned = canonical[2]
        model.arrangeHand(.ascending)
        let presentation = model.handPresentationOrder
        model.tapHandCard(returned.id)
        model.tapSquare(square)
        XCTAssertEqual(model.lastOutcome?.returnedToHand, true)
        XCTAssertEqual(model.handCards.map(\.id), [canonical[0].id, canonical[1].id, canonical[3].id, returned.id])
        XCTAssertEqual(model.handPresentationOrder, presentation)
        XCTAssertEqual(model.numberReturns.last?.handCardIDs, [returned.id])
        assertCompletePermutation(model)
    }

    func testSortedWrongPlacementRemovesOnlyTheReturnedCopy() throws {
        let model = try makeModel()
        let selected = model.handCards[2]
        model.arrangeHand(.descending)
        let square = try XCTUnwrap(model.puzzle?.board.blanks.first {
            model.puzzle?.board.correctDigit(at: $0) != selected.digit
        })
        model.tapHandCard(selected.id)
        model.tapSquare(square)
        XCTAssertEqual(model.lastOutcome?.correct, false)
        XCTAssertFalse(model.handPresentationOrder.contains(selected.id))
        XCTAssertEqual(model.numberReturns.last?.handCardIDs, [selected.id])
        XCTAssertEqual(model.handCards.filter { $0.digit == selected.digit }.count, 1)
        assertCompletePermutation(model)
    }

    func testSortedMarkerDrawAndRedrawReconcileWithTheCanonicalHand() throws {
        var game = try fixture()
        let digit = try XCTUnwrap(game.puzzle?.hand[2])
        let square = try XCTUnwrap(game.puzzle?.board.blanks.first {
            game.puzzle?.board.correctDigit(at: $0) == digit
        })
        game.qaSetMarker("mk_sapphire", at: square)
        let model = GameModel(resuming: game, savesProgress: false)
        model.arrangeHand(.descending)
        model.tapHandCard(model.handCards[2].id)
        model.tapSquare(square)
        XCTAssertEqual(model.lastOutcome?.numbersDrawn, 1)
        XCTAssertEqual(model.displayedHandCards.map(\.digit), model.hand.sorted(by: >))
        model.qaSetBuff(Buffs.redraw)
        let old = model.handCards.map(\.id)
        XCTAssertTrue(model.useBuff(at: 0))
        XCTAssertTrue(Set(old).isDisjoint(with: model.handPresentationOrder))
        XCTAssertEqual(model.numberReturns.last?.handCardIDs, old)
        XCTAssertEqual(model.displayedHandCards.map(\.digit), model.hand.sorted(by: >))
        assertCompletePermutation(model)
    }

    func testFinalCardAutomaticTurnRefillReconcilesOnceWithSortedPresentation() throws {
        var run = try fixture().run
        var puzzle = try XCTUnwrap(run.puzzle)
        for digit in puzzle.hand.dropFirst() { puzzle.pool.put(digit) }
        puzzle.hand = Array(puzzle.hand.prefix(1))
        puzzle.target = 100_000
        run.puzzle = puzzle
        let model = GameModel(resuming: Game(run: run), savesProgress: false)
        model.arrangeHand(.ascending)
        let selected = try XCTUnwrap(model.handCards.first)
        let turn = puzzle.turnNumber
        let square = try blank(in: model, matching: selected.digit)
        model.tapHandCard(selected.id)
        model.tapSquare(square)
        XCTAssertEqual(model.puzzle?.turnNumber, turn + 1)
        XCTAssertFalse(model.handPresentationOrder.contains(selected.id))
        XCTAssertEqual(model.displayedHandCards.map(\.digit), model.hand.sorted())
        let before = model.game
        model.tapHandCard(selected.id) // An old tile's delayed tap is ignored.
        XCTAssertNil(model.selectedHandIndex)
        XCTAssertNil(RunStore.conflict(local: before, remote: model.game))
        assertCompletePermutation(model)
    }

    func testPresentationResumeRestoresRandomPermutationAndRejectsStaleOrDifferentRun() throws {
        let model = try makeModel()
        model.arrangeHand(.random)
        let saved = try XCTUnwrap(model.handPresentation)
        let encoded = try JSONEncoder().encode(saved)
        let restored = try JSONDecoder().decode(GameModel.HandPresentation.self, from: encoded)
        let resumed = GameModel(resuming: try Game(decoding: model.game.encoded()), savesProgress: false)
        let gameBefore = resumed.game
        XCTAssertTrue(resumed.restoreHandPresentation(restored))
        XCTAssertEqual(resumed.handCards, model.handCards)
        XCTAssertEqual(resumed.handPresentationOrder, model.handPresentationOrder)
        XCTAssertEqual(resumed.handArrangement, .random)
        XCTAssertNil(RunStore.conflict(local: gameBefore, remote: resumed.game))
        resumed.endTurn()
        let newOrder = resumed.handPresentationOrder
        XCTAssertFalse(resumed.restoreHandPresentation(restored))
        XCTAssertEqual(resumed.handPresentationOrder, newOrder)
        var other = Game(seed: "different-arrangement-run")
        try other.startPuzzle()
        XCTAssertFalse(GameModel(resuming: other, savesProgress: false).restoreHandPresentation(restored))
    }

    private func makeModel() throws -> GameModel {
        GameModel(resuming: try fixture(), savesProgress: false)
    }

    private func fixture() throws -> Game {
        var game = Game(seed: "hand-arrangement", book: .noPressure)
        try game.startPuzzle()
        var run = game.run
        var puzzle = try XCTUnwrap(run.puzzle)
        for digit in puzzle.hand { puzzle.pool.put(digit) }
        let duplicate = try XCTUnwrap(Digit.all.reversed().first { puzzle.pool[$0] >= 2 })
        let others = Digit.all.filter { $0 != duplicate && puzzle.pool[$0] > 0 }
        XCTAssertGreaterThanOrEqual(others.count, 2)
        puzzle.hand = []
        puzzle.handSize = 4
        puzzle.cluesRemaining = 2
        for digit in [duplicate, others[0], duplicate, others[1]] {
            XCTAssertTrue(puzzle.pool.take(digit))
            puzzle.hand.append(digit)
        }
        run.puzzle = puzzle
        return Game(run: run)
    }

    private func blank(in model: GameModel, matching digit: Digit) throws -> Square {
        try XCTUnwrap(model.puzzle?.board.blanks.first { model.puzzle?.board.correctDigit(at: $0) == digit })
    }

    private func streamStates(_ game: Game) -> [UInt32] {
        [game.run.streams.board.state, game.run.streams.pool.state,
         game.run.streams.shop.state, game.run.streams.boss.state]
    }

    private func assertCompletePermutation(_ model: GameModel,
                                           file: StaticString = #filePath, line: UInt = #line) {
        XCTAssertEqual(model.handCards.map(\.digit), model.hand, file: file, line: line)
        XCTAssertEqual(Set(model.handPresentationOrder), Set(model.handCards.map(\.id)), file: file, line: line)
        XCTAssertEqual(model.handPresentationOrder.count, model.handCards.count, file: file, line: line)
        XCTAssertEqual(model.displayedHandCards.count, model.handCards.count, file: file, line: line)
    }
}
