import SwiftUI
import NumberClubEngine

/// The shelf. You arrive here on launch, and come back whenever a Book ends or
/// is abandoned — §3 makes the Starting Board a choice you make when you open a
/// Book, so one is never dealt silently.
///
/// Books are swiped through rather than listed. Only the written one can be
/// opened; the rest are locked and shown anyway, so the ladder §2 leaves
/// undecided is visible instead of implied.
struct StartBookView: View {
    var onStart: (StartingBoard) -> Void

    @State private var index = 0
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    private var books: [BookEdition] { BookEdition.shelf }
    private var book: BookEdition { books[min(index, books.count - 1)] }

    var body: some View {
        ZStack(alignment: .bottom) {
            ShelfBackdrop(book: book, reduceMotion: reduceMotion)

            TabView(selection: $index) {
                ForEach(Array(books.enumerated()), id: \.offset) { position, edition in
                    BookOnDesk(book: edition)
                        .tag(position)
                }
            }
            .tabViewStyle(.page(indexDisplayMode: .never))

            controls
        }
        .background(Paper.deskDark)
        .preferredColorScheme(.dark)
        .statusBarHidden()
        .animation(.easeInOut(duration: 0.35), value: index)
    }

    private var controls: some View {
        VStack(spacing: 12) {
            PageDots(count: books.count, index: index)

            // What the Book gives you. §3's boards are not a separate choice
            // — the Book you pick up is the board you play on.
            VStack(spacing: 3) {
                Text(book.isWritten ? book.shelfLabel : "Not written yet")
                    .font(Print.caption(10))
                    .tracking(1.8)
                    .textCase(.uppercase)
                    .foregroundStyle(Paper.page.opacity(0.5))

                Text(book.bonusText)
                    .font(Print.body(13))
                    .foregroundStyle(Paper.page.opacity(0.82))
            }

            if book.isWritten {
                PaperButton(title: "Open the Book", kind: .primary) { onStart(book.bonus) }
            } else {
                PaperButton(title: "Locked", kind: .quiet, isEnabled: false) {}
            }
        }
        .padding(.horizontal, 24)
        .padding(.bottom, 26)
    }
}

/// Which Book you are looking at, and how many there are.
private struct PageDots: View {
    var count: Int
    var index: Int

    var body: some View {
        HStack(spacing: 7) {
            ForEach(0..<count, id: \.self) { position in
                Circle()
                    .fill(Paper.page.opacity(position == index ? 0.85 : 0.28))
                    .frame(width: position == index ? 7 : 5,
                           height: position == index ? 7 : 5)
            }
        }
        .animation(.snappy(duration: 0.2), value: index)
        .accessibilityLabel("Book \(index + 1) of \(count)")
    }
}

// MARK: - Backdrop

/// Deliberately not a photograph of a desk: the covers are already
/// photographed lying on one, and two desks read as a picture of a book rather
/// than as a book. It takes a wash of whichever Book is in front of you.
private struct ShelfBackdrop: View {
    var book: BookEdition
    var reduceMotion: Bool
    @State private var drifted = false

    var body: some View {
        GeometryReader { proxy in
            ZStack {
                Color(hex: 0x120D0A)

                // The desk itself: shot for this screen, in phone format, with
                // the props at the very edges and the middle left bare for the
                // Book to lie on. Generated by scripts/gen-desk.mjs.
                Image("Desk")
                    .resizable()
                    .aspectRatio(contentMode: .fill)
                    .frame(width: proxy.size.width, height: proxy.size.height)
                    .scaleEffect(drifted ? 1.05 : 1.0)
                    .clipped()

                // The Book in front tints the light falling on the desk.
                RadialGradient(
                    colors: [book.accent.opacity(0.14), .clear],
                    center: .init(x: 0.14, y: 0.08),
                    startRadius: 10, endRadius: proxy.size.height * 0.75
                )
                .blendMode(.plusLighter)

                // Just enough shade at the foot for the controls to sit on.
                LinearGradient(
                    stops: [
                        .init(color: .black.opacity(0.30), location: 0),
                        .init(color: .clear, location: 0.16),
                        .init(color: .clear, location: 0.62),
                        .init(color: .black.opacity(0.62), location: 0.85),
                        .init(color: .black.opacity(0.88), location: 1),
                    ],
                    startPoint: .top, endPoint: .bottom
                )
            }
        }
        .ignoresSafeArea()
        .accessibilityHidden(true)
        .animation(.easeInOut(duration: 0.45), value: book.id)
        .onAppear {
            guard !reduceMotion else { return }
            withAnimation(.easeInOut(duration: 26).repeatForever(autoreverses: true)) {
                drifted = true
            }
        }
    }
}

/// One Book lying on the desk, whole. It is a cover — cropping it to fill a
/// phone throws away the tabs, the notes and half the title.
private struct BookOnDesk: View {
    var book: BookEdition
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    private var playsLoop: Bool {
        !reduceMotion && !ProcessInfo.processInfo.isLowPowerModeEnabled
    }

    var body: some View {
        // The cover is width-bound on a phone, so it can never fill the height.
        // Centring it in what is left puts the slack above and below instead of
        // dumping all of it under the Book.
        Group {
            if let cover = book.cover {
                ZStack {
                    // The still is always underneath, so the Book is painted
                    // before any decoder has started and there is never a
                    // black flash — and so a Book without a loop still works.
                    Image(cover)
                        .resizable()
                        .aspectRatio(contentMode: .fit)

                    if let loop = book.loop, playsLoop,
                       let url = Bundle.main.url(forResource: loop, withExtension: "mp4") {
                        LoopingVideo(url: url)
                            .aspectRatio(968.0 / 1330.0, contentMode: .fit)
                    }
                }
            } else {
                UnwrittenCover(book: book)
                    .aspectRatio(968.0 / 1330.0, contentMode: .fit)
            }
        }
        .clipShape(RoundedRectangle(cornerRadius: 4))
        .shadow(color: .black.opacity(0.65), radius: 28, x: 6, y: 18)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .padding(.horizontal, 18)
        .padding(.top, 10)
        .padding(.bottom, 120)
        .accessibilityLabel(book.isWritten
            ? "\(book.title), \(book.shelfLabel)"
            : "\(book.title), not written yet")
    }
}

/// A Book that has not been written: cloth, a blocked title, a lock, and
/// nothing else that would promise something which does not exist.
private struct UnwrittenCover: View {
    var book: BookEdition

    var body: some View {
        ZStack {
            LinearGradient(colors: [book.accent.opacity(0.55), Color(hex: 0x221E1A)],
                           startPoint: .topLeading, endPoint: .bottomTrailing)

            // Blind-stamped rules, the way a plain cloth binding is finished.
            RoundedRectangle(cornerRadius: 2)
                .strokeBorder(.white.opacity(0.10), lineWidth: 1)
                .padding(18)

            VStack(spacing: 14) {
                Image(systemName: "lock")
                    .font(.system(size: 24, weight: .light))
                    .foregroundStyle(Paper.page.opacity(0.45))
                Text(book.title)
                    .font(Print.heading(27))
                    .foregroundStyle(Paper.page.opacity(0.78))
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 26)
                Text(book.shelfLabel)
                    .font(Print.caption(10))
                    .tracking(1.8)
                    .textCase(.uppercase)
                    .foregroundStyle(Paper.page.opacity(0.35))
            }
        }
    }
}
